# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps
components/esp_stdio/test_apps/stdio:
  disable:
    - if: CONFIG_NAME == "serial_jtag_only" and SOC_USB_SERIAL_JTAG_SUPPORTED != 1
    - if: CONFIG_NAME == "serial_jtag_only_no_vfs" and SOC_USB_SERIAL_JTAG_SUPPORTED != 1
    - if: CONFIG_NAME == "stdio_no_vfs" and SOC_USB_SERIAL_JTAG_SUPPORTED != 1
  disable_test:
    - if: CONFIG_NAME == "simple" and IDF_TARGET != "esp32"
