# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/app_trace/test_apps:
  depends_components:
    - app_trace
    - esp_timer
    - soc
    - esp_hw_support
    - esp_driver_uart
    - esp_driver_gptimer
  disable:
    - if: IDF_TARGET in ["esp32h21", "esp32h4"]
      temporary: true
      reason: not support yet # TODO: [ESP32H21] IDF-11539 [ESP32H4] IDF-12325
