# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/app_update/test_apps:
  disable:
    - if: IDF_TARGET in ["esp32c61"]
      temporary: true
      reason: target esp32c61 is not supported yet  # TODO: [ESP32C61] IDF-9245
